import { MRSLClassCode } from "./types";

export const MRSL_CLASS_CODES: MRSLClassCode[] = [
  { code: "AD", description: "Average Disbursements" },
  { code: "AL", description: "Commercial Automobile Liability" },
  { code: "AV", description: "Aviation" },
  { code: "BR", description: "Builders Risks" },
  { code: "CA", description: "Cargo" },
  { code: "CC", description: "Commercial Combined" },
  { code: "CD", description: "Custom Duty" },
  { code: "CI", description: "Cash In Transit" },
  { code: "CL", description: "Charterers Liability" },
  { code: "CN", description: "Contract Cancellation & Non-Appearance" },
  { code: "CP", description: "Contractors Plant & Equipment" },
  { code: "CR", description: "Construction All Risks" },
  { code: "CT", description: "Charterers Default" },
  { code: "CY", description: "Cyber Insurance" },
  { code: "D0", description: "Directors & Officers" },
  { code: "DI", description: "Disbursements" },
  { code: "DS", description: "Death In Service" },
  { code: "EC", description: "Legal Indemnities / Expenses Cover" },
  { code: "EG", description: "Energy" },
  { code: "EI", description: "Engineering" },
  { code: "EP", description: "Excess PL" },
  { code: "F", description: "Financial" },
  { code: "FA", description: "Fine Art" },
  { code: "FS", description: "Failure to Survive" },
  { code: "GM", description: "Medical Malpractice" },
  { code: "HA", description: "Agricultural Crop and Forestry" },
  { code: "HM", description: "Hull and Machinery" },
  { code: "IV", description: "Increased Value" },
  { code: "KD", description: "Kidnap & Ransom" },
  { code: "KR", description: "Kidnap & Ransom" },
  { code: "LE", description: "Legal Expenses" },
  { code: "LF", description: "Life" },
  { code: "LH", description: "Loss of Hire" },
  { code: "LI", description: "Liability" },
  { code: "LV", description: "Livestock" },
  { code: "ME", description: "Medical Expenses" },
  { code: "MF", description: "Overseas Motor" },
  { code: "MI", description: "Marine Interest" },
  { code: "MO", description: "Mortgagees Interest" },
  { code: "OM", description: "Overseas Motor" },
  { code: "PA", description: "Personal Accident" },
  { code: "PI", description: "Protection & Indemnity" },
  { code: "PL", description: "Public & Product Liability" },
  { code: "PO", description: "Professional Indemnity" },
  { code: "PR", description: "Property" },
  { code: "PT", description: "Ports & Terminals" },
  { code: "PV", description: "Political Violence" },
  { code: "QS", description: "Quota Share Reinsurance" },
  { code: "SD", description: "Safe Deposit Box (Re)Insurance" },
  { code: "SP", description: "General Specie & Property R/I" },
  { code: "TE", description: "Terrorism" },
  { code: "TP", description: "Terrorism / Political Risks" },
  { code: "W6", description: "US Workers Compensation Cat Exposure" },
  { code: "WR", description: "War Risks" },
  { code: "XL", description: "Excess of Loss" },
  { code: "XX", description: "Additional Record" },
];

export const WEBHOOK_URL = "https://primary-production-d2b7.up.railway.app/webhook/a81c7307-1d1a-4824-ae01-6db2ff46abcb";
